[Dev-19] Tier package keeper coverage was increased
elys-network/elys pull request #1006
Opened 2024-11-28 19:30 UTC by fenriz07

[Dev-19] Tier package keeper coverage was increased

2024-12-04 12:02 UTC, avkr003 requested changes

2024-12-04 12:02 UTC, avkr003 commented on Makefile
> +VERSION:=v999.999.999
Why overwriting this change. This is used -X github.com/cosmos/cosmos-sdk/version.Version=$(VERSION) \ which goes into binary and upgrades are based on this.

2024-12-04 12:14 UTC, amityadav0 commented on x/tier/keeper/keeper_test.go
> +		},*/
do we need this ?

2024-12-04 12:15 UTC, amityadav0 commented on Makefile
> +VERSION:=v999.999.999
```suggestion
VERSION:=$(shell git describe --tags --match 'v*' --abbrev=8 | sed 's/-g/-/' | sed 's/-[0-9]*-/-/')
```

2024-12-06 12:18 UTC, amityadav0 approved these changes

2024-12-07 17:49 UTC, cosmic-vagabond approved these changes

2024-12-07 17:49 UTC, merged