feat: update leveragelp pool
elys-network/elys pull request #673
Opened 2024-07-25 13:20 UTC by cryptokage1996

## Description

Closes:
*https://trello.com/c/HwkuOSkf/403-leveragelp-pool-update

### What has Changed?

updated tx for leveragelp disable or enable existing pool
added tx for dding new pools 

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/elys-network/elys/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/elys-network/elys/blob/main/docs/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/elys-network/elys/blob/main/CONTRIBUTING.md#testing)
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### Deployment Notes

Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in a deployed environment.

### Screenshots and Videos

Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial in demonstrating the process.

2024-07-26 10:00 UTC, amityadav0 requested changes

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/client/cli/tx_add_pool.go
> +		return types.Pool{}, err
When creating new pool, I think we should use default values for lpAmount and health. In current case governance can set health or lpAmount to anything

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_add_pool.go
> +	_, found := k.GetPool(ctx, msg.Pool.AmmPoolId)
Please add a check here `Pool.AmmPoolId should be oracle enabled`

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_remove_pool.go
> +
Please add some checks here, we should not be able to delete Pool with lpAmount > 0

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_remove_pool.go
> +func (k msgServer) RemovePool(goCtx context.Context, msg *types.MsgAddPool) (*types.MsgAddPoolResponse, error) {
Why are we using `types.MsgAddPool ` here ?

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_update_pools.go
> +		pool.Closed = msg.Pool.Closed
I think we don't need whole pool object values when updating, please update it to use required values which are `Enabled` / `Closed` and `PoolId`

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_update_pools.go
> +	pool, found := k.GetPool(ctx, msg.Pool.AmmPoolId)
This should be pool id of pool in leveragelp

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_update_pools.go
> +	pool, found := k.GetPool(ctx, msg.Pool.AmmPoolId)
not AmmPoolId in leveragelp

2024-07-26 10:00 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_remove_pool.go
> +		k.DeletePool(ctx, msg.Pool.AmmPoolId)
we should accept a single number which is pool id instead of whole pool object

2024-07-26 11:36 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_update_pools.go
> +	pool, found := k.GetPool(ctx, msg.Pool.AmmPoolId)
thanks

2024-07-26 11:37 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_update_pools.go
> +		pool.Closed = msg.Pool.Closed
okay, we don't need `pool` object here

2024-07-29 19:04 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_add_pool.go
> +			k.SetPool(ctx, newPool)
need to initialise other values too, lpAmount should be zero etc

2024-07-29 19:05 UTC, amityadav0 commented on x/leveragelp/types/errors.go
> +	ErrPoolLevrageAmountNotZero= errorsmod.Register(ModuleName, 41, "pools leverage amount is grater than zero")
```suggestion
	ErrPoolLeverageAmountNotZero= errorsmod.Register(ModuleName, 41, "pool leverage amount is greater than zero")
```

2024-07-30 06:51 UTC, amityadav0 commented
Please add screenshots of these operations after testing.

2024-07-30 14:39 UTC, cosmic-vagabond approved these changes

2024-07-30 14:39 UTC, merged