Dev 2033 add updated leverage value
elys-network/elys pull request #853
Opened 2024-10-09 09:39 UTC by cryptokage1996

2024-10-10 15:09 UTC, cosmic-vagabond commented
@cryptokage1996 please fix conflicts and add test cases for both long and short positions thanks

2024-10-11 15:48 UTC, cosmic-vagabond commented on x/perpetual/client/cli/query_mtp_test.go
> +			UpdatedLeverage:   sdk.ZeroDec(),
@cryptokage1996 can you share a test result where the new `updated leverage` field return a positive value for an existing position thanks

2024-10-16 17:51 UTC, cosmic-vagabond requested changes

2024-10-16 17:51 UTC, cosmic-vagabond commented on x/perpetual/keeper/updated_leverage.go
> +	collateral_in_usdc := math.LegacyDec(mtp.Collateral)
@cryptokage1996 long position’s collateral can be in terms of both base currency or trading asset, we have to make sure it is in base currency

2024-10-17 09:36 UTC, cosmic-vagabond requested changes

2024-10-17 09:36 UTC, cosmic-vagabond commented on x/perpetual/keeper/updated_leverage.go
> +		price := k.amm.EstimatePrice(ctx, mtp.CustodyAsset, baseCurrency)
@cryptokage1996 price is queried twice line 20 and 25 can we remove this redundancy? thanks

2024-10-17 09:38 UTC, cosmic-vagabond commented on x/perpetual/keeper/updated_leverage.go
> +		price := k.amm.EstimatePrice(ctx, mtp.CustodyAsset, baseCurrency)
@cryptokage1996 can you also fix the conflicts in this PR thanks

2024-10-17 13:23 UTC, avkr003 requested changes

2024-10-17 13:23 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	collateral_in_usdc := math.LegacyDec(mtp.Collateral)
incorrect code, you are type casting Into to Dec, Use ToLegacyDec

2024-10-17 13:23 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	liablites := math.LegacyDec(mtp.Liabilities)
same as above, please see if you have done this anywhere else and correct it

2024-10-21 15:55 UTC, cosmic-vagabond commented
@cryptokage1996 there are multiple unit tests that are failing

2024-10-21 16:28 UTC, Wgil commented
lets not merge this before https://github.com/elys-network/elys/pull/867

2024-10-22 08:31 UTC, avkr003 requested changes

2024-10-22 08:35 UTC, avkr003 approved these changes

2024-10-22 08:35 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	updated_leverage := liablites.Quo(collateral_in_usdc).Add(sdk.OneDec())
Change from 1 + liabilities/collateral to custody / (custody - liabilites)

2024-10-22 08:37 UTC, avkr003 requested changes

2024-10-22 08:37 UTC, avkr003 commented on proto/elys/perpetual/query.proto
> +  string updated_leverage = 4 [
based on new formula, it should be `effective_leverage` as we won't be using collateral

2024-10-22 10:29 UTC, avkr003 requested changes

2024-10-22 10:29 UTC, avkr003 commented on x/perpetual/types/expected_keepers.go
> +	GetUsdcDenom(ctx sdk.Context) (usdcDenom string, found bool)
Can remove this if not being used

2024-10-22 10:29 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	priceBaseCurrency := k.oracleKeeper.GetAssetPriceFromDenom(ctx, baseCurrency)
No need. Base currency is usdc so price is 1

2024-10-22 10:29 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	if priceBaseCurrency.IsZero() {
It's never 0

2024-10-22 10:29 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	denominator := custodyInUsdc.Sub(mtp.Liabilities.ToLegacyDec())
Incorrect. For short, liabilities will be trading in asset, can't subtract different units

2024-10-22 10:29 UTC, avkr003 commented on x/perpetual/keeper/updated_leverage.go
> +	}
Too complicated. Check in other places how tradingAssetPrice is fetched.

2024-10-22 13:09 UTC, avkr003 approved these changes

2024-10-22 13:17 UTC, merged