Dev 1929 stable stake pool max leverage
elys-network/elys pull request #858
Opened 2024-10-14 10:02 UTC by cryptokage1996

2024-10-15 09:02 UTC, amityadav0 commented on x/leveragelp/keeper/msg_server_open.go
> +		borrowRatio = sdk.NewDecFromInt(borrowed).Add(msg.Leverage.Mul(msg.CollateralAmount.ToLegacyDec())).
I think we need to multiply It with 100 here or use 0.7 in params.MaxLeveragePercent

2024-10-16 02:23 UTC, cosmic-vagabond requested changes

2024-10-16 02:23 UTC, cosmic-vagabond commented on x/leveragelp/keeper/msg_server_open.go
> +		return nil, errors.New("pool is already leveraged at maximum value")
@cryptokage1996 can you define this new error within `types/errors.go` thanks

2024-10-16 17:47 UTC, cosmic-vagabond approved these changes

2024-10-16 17:47 UTC, merged