Pools should not be created with more than two assets
elys-network/elys pull request #859
Opened 2024-10-14 16:27 UTC by fenriz07

2024-10-14 17:59 UTC, avkr003 requested changes

2024-10-14 17:59 UTC, avkr003 commented on x/amm/types/message_create_pool.go
> +	if len(msg.PoolAssets) != 2 {
Can use `if len(msg.PoolAssts) > 2 || len(msg.PoolAssets) < 2`
Cover both sides.

2024-10-14 18:01 UTC, avkr003 approved these changes

2024-10-15 03:25 UTC, cosmic-vagabond approved these changes

2024-10-15 03:25 UTC, merged