Exported genesis validation fix
elys-network/elys pull request #934
Opened 2024-11-13 14:25 UTC by 99adarsh

### Description
AMM pool addresses and pool share denom metadata in the bank module were getting invalidated during validate genesis because,
-  the amm pool module account name was incorrect to get module account validated in auth module genesis validator
-  the pool share denom Metadata did not contain the name and symbol

### Added the following
Migration script code -

- Created a migration script which will iterate over all the amm pool, create new address and corresponding account without derivation key, transfer funds from previous amm pool account to new one and update the authority in the assetProfile entry.
- It will also update the DenomMetadata in the bank module by adding name and symbol.

2024-11-18 22:11 UTC, avkr003 requested changes

2024-11-18 22:11 UTC, avkr003 commented on x/amm/migrations/v7_migration.go
> +			panic(fmt.Errorf("error creating new pool account for %d: %w", pool.PoolId, err))
return error

2024-11-18 22:11 UTC, avkr003 commented on x/amm/migrations/v7_migration.go
> +			panic(fmt.Errorf("assetprofile not found for basedenom: %s", poolBaseDenom))
same as above

2024-11-18 22:11 UTC, avkr003 commented on x/amm/migrations/v7_migration.go
> +			panic(fmt.Errorf("denom metadata for poolshare denom not found in bank denom metadata: %s", poolBaseDenom))
same as above

2024-11-20 18:49 UTC, cosmic-vagabond approved these changes

2024-11-20 18:50 UTC, merged